version: '3'

x-env: &env
  environment:
    - MYSQL_ROOT_PASSWORD # required by mysql
    - MYSQL_HOST
    - MYSQL_USER
    - MYSQL_PASSWORD
    - MYSQL_DATABASE

services:
  nginx:
    container_name: nginx
    depends_on:
      - php
    build:
      context: ./docker/nginx/
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app:/var/www/html:z
    ports:
      - 80:80
      - 443:443
    networks:
      - app-network
  php:
    <<: *env
    container_name: php
    build:
      context: ./docker/php/
    volumes:
    - ./app:/var/www/html:z
    ports:
      - ":9000"
    networks:
      - app-network
  mysql:
    <<: *env
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    build:
      context: ./docker/mysql/
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  mysql: