version: '3'

services:
  nginx:
    container_name: nginx
    depends_on:
      - php
    build:
      context: ./docker/nginx/
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app:/var/www/html:z
    ports:
      - 80:80
      - 443:443
    networks:
      - app-network
  php:
    container_name: php
    build:
      context: ./docker/php/
    volumes:
    - ./app:/var/www/html:z
    ports:
      - ":9000"
    networks:
      - app-network
  mysql:
    container_name: mysql
    environment:
    - MYSQL_ROOT_USER
    - MYSQL_ROOT_PASSWORD
    - MYSQL_DATABASE
    ports:
      - ":3306"
    build:
      context: ./docker/mysql/
    networks:
      - app-network
networks:
  app-network:
    driver: bridge