version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx/
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app:/var/www/html:z
    networks:
      - app-network

networks:
  app-network:
    driver: bridge