# Dockerfile for Nginx

# Use the official Nginx image as the base image
FROM nginx:latest

# Copy the custom Nginx configuration file to the container
COPY ./nginx.conf /etc/nginx/nginx.conf

# Expose ports for incoming HTTP traffic
EXPOSE 80 443